---
platform: linux

image_resource:
  type: registry-image
  source: {repository: golang}

inputs:
  - name: ansi

params:
  ACTION:
  FUZZIT_API_KEY:

caches:
  - path: gopath

run:
  path: ansi/ci/tasks/scripts/fuzzit.sh