jobs:
  - name: test
    plan:
      - get: ansi
      - task: unit
        file: ansi/ci/tasks/unit.yml
  - name: fuzz
    plan:
      - get: ansi
      - task: local-regression
        file: ansi/ci/tasks/fuzzit.yml
        params:
          ACTION: local-regression
          FUZZIT_API_KEY: ((aidan-fuzzit-apikey))
      - task: fuzzing
        file: ansi/ci/tasks/fuzzit.yml
        params:
          ACTION: fuzzing
          FUZZIT_API_KEY: ((aidan-fuzzit-apikey))


resources:
  - name: ansi
    type: git
    icon: github-circle
    source:
      uri: https://github.com/aoldershaw/ansi.git
      branch: master